from __future__ import annotations

DEFAULT_AGENT_PROFILES = [
    {
        "id": "agent_manager",
        "name": "Manager",
        "role": "manager",
        "defaultTools": ["plan", "review"],
        "station": "manager",
        "accent": "#277f71",
        "personality": "Calm coordinator who plans and synthesizes.",
        "taskPriority": 9,
    },
    {
        "id": "agent_browser",
        "name": "Browser",
        "role": "browser",
        "defaultTools": ["browser", "search"],
        "station": "browser",
        "accent": "#3f7fb0",
        "personality": "Curious researcher who reads the web.",
        "taskPriority": 6,
    },
    {
        "id": "agent_computer",
        "name": "Computer",
        "role": "computer",
        "defaultTools": ["computer"],
        "station": "computer",
        "accent": "#9a5b2d",
        "personality": "Hands-on operator of the desktop.",
        "taskPriority": 6,
    },
    {
        "id": "agent_file",
        "name": "File",
        "role": "file",
        "defaultTools": ["file"],
        "station": "file",
        "accent": "#5b8d55",
        "personality": "Tidy organizer of the workspace.",
        "taskPriority": 5,
    },
    {
        "id": "agent_reviewer",
        "name": "Reviewer",
        "role": "reviewer",
        "defaultTools": ["review"],
        "station": "reviewer",
        "accent": "#b65c2f",
        "personality": "Careful checker of quality and risk.",
        "taskPriority": 7,
    },
    {
        "id": "agent_terminal",
        "name": "Terminal",
        "role": "terminal",
        "defaultTools": ["terminal", "docker"],
        "station": "terminal",
        "accent": "#6a6f86",
        "personality": "Precise runner of sandboxed commands.",
        "taskPriority": 4,
    },
]
