from __future__ import annotations

from typing import Iterator, Protocol

from yanshi_runtime.models import ChatMessage, ProviderHealth


class Provider(Protocol):
    """The provider surface the runtime graph + service depend on. Both OpenAICompatibleProvider
    and AnthropicProvider implement it; the graph holds one behind this interface."""

    @property
    def configured(self) -> bool: ...
    @property
    def public_base_url(self) -> str | None: ...
    @property
    def model(self) -> str | None: ...

    def update_config(self, config: object) -> None: ...
    def list_models(self) -> list[str]: ...
    def healthcheck(self) -> ProviderHealth: ...
    def chat_completion(self, messages: list[ChatMessage], model: str | None = None) -> str: ...
    def stream_chat_completion(self, messages: list[ChatMessage], model: str | None = None) -> Iterator[str]: ...
